project:
  type: website

website:
  title: "Mi Portafolio"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Proyectos"
        menu:
          - text: "Proyecto 1"
            href: projects/Project_01/README.md
          - text: "Proyecto 2"
            href: projects/Project_02/README.md
          - text: "Proyecto 3"
            href: projects/Project_03/README.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
