---
title: "Mi Portafolio de Proyectos"
---

# Bienvenido a Mi Portafolio de Proyectos

Soy un científico de datos recién egresado con experiencia en diversos proyectos de análisis de datos y machine learning. A continuación, encontrarás enlaces a algunos de mis trabajos destacados.

## Proyectos

### [Project 1: Fake News Detector Based on Neural Networks](.Projects/Project_01)
- **Description**: Exploratory data analysis using pandas and matplotlib. Data engineering and text processing. Deep learning.
- **Technologies**: Python, pandas, numpy, scikit-learn, matplotlib, seaborn, tensorflow keras.

### [Project 2: Customer Segmentation for Financial Product](.Projects/Project_02)
- **Description**: This project focuses on the exploration and analysis of data using clustering techniques and principal component analysis (PCA). Algorithms such as K-Means, Hierarchical Clustering, and Spectral Clustering are used to identify patterns and groupings in the data.
- **Technologies**: Python, pandas, numpy, scikit-learn, matplotlib, seaborn, scipy, plotly.

### [Project 3: Salary Prediction and Classification for Job Applicants](.Projects/Project_03)
- **Description**: This project involves the development of two models: one for predicting the expected salary of job applicants based on their characteristics, and another for classifying whether an applicant is likely to be hired. The project includes data exploration, feature transformation, and model building for both regression and classification tasks.
- **Technologies**: Python, pandas, numpy, scikit-learn, matplotlib, seaborn, Jupyter Notebooks


## How to Run the Projects

Each project has its own folder and contains a `README.md` with detailed instructions on how to run the code. Below is a general example of how to clone the repository and install the necessary dependencies:

1. Clone the repository:
    ```sh
    git clone https://github.com/luismmachados/Portfolio_projects
    ```

2. Navigate to the project directory:
    ```sh
    cd Portfolio_projects
    ```

3. Install the dependencies:
    ```sh
    pip install -r requirements.txt
    ```

4. Run the project's main script:
    ```sh
    python scripts/analysis.py
    ```

## Contact

- **LinkedIn**: [Luis Manuel Machado](https:/www.linkedin.com/in/luismmachados)
- **Email**: luismachado.mmachado@gmail.com

---

Thank you for visiting my portfolio! Feel free to contact me if you have any questions or if you would like to discuss potential collaboration opportunities.
