project:
  type: website
  title: "Mi Portafolio de Proyectos"

website:
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Proyectos"
        menu:
          - text: "Proyecto 1"
            href: projects/project1/README.md
          - text: "Proyecto 2"
            href: projects/project2/README.md
  format:
    html:
      theme: cosmo
      css: styles.css
